export const UI_COPY = {
  mainMenu: {
    title: 'Google Accounts (Antigravity)',
    searchSubtitlePrefix: 'Search:',
    quickStart: 'Quick Actions',
    addAccount: 'Add New Account',
    checkAccounts: 'Check Quotas',
    bestAccount: 'Best Account',
    verifyOneAccount: 'Verify One Account',
    configureModels: 'Configure Models',
    geminiCliLogin: 'Gemini CLI Login',
    checkFlagged: 'Check Problem Accounts',
    settings: 'Settings',
    moreChecks: 'Advanced Checks',
    refreshChecks: 'Refresh All Accounts',
    accounts: 'Saved Accounts',
    loadingLimits: 'Fetching account limits...',
    noSearchMatches: 'No accounts match your search',
    dangerZone: 'Danger Zone',
    removeAllAccounts: 'Delete All Accounts',
    helpCompact: '↑↓ Move | Enter Select | / Search | 1-9 Switch | Q Back',
    helpDetailed: 'Arrow keys move, Enter selects, / searches, 1-9 switches account, Q goes back',
  },
  accountDetails: {
    back: 'Back',
    enable: 'Enable Account',
    disable: 'Disable Account',
    setCurrent: 'Set As Current',
    refresh: 'Re-Login',
    remove: 'Delete Account',
    help: '↑↓ Move | Enter Select | S Use | R Sign In | D Delete | Q Back',
  },
  oauth: {
    chooseModeTitle: 'Sign-In Method',
    chooseModeSubtitle: 'How do you want to sign in?',
    openBrowser: 'Open Browser (Easy)',
    manualMode: 'Manual / Incognito',
    back: 'Back',
    chooseModeHelp: '↑↓ Move | Enter Select | 1 Easy | 2 Manual | Q Back',
    goTo: 'Go to:',
    copyOk: 'Login link copied.',
    copyFail: 'Could not copy login link.',
    pastePrompt: 'Paste callback URL or code here (Q to cancel):',
    browserOpened: 'Browser opened.',
    browserOpenFail: 'Could not open browser. Use this link:',
    waitingCallback: 'Waiting for login callback on localhost:1455...',
    callbackMissed: 'No callback received. Paste manually.',
    cancelled: 'Sign-in cancelled.',
    cancelledBackToMenu: 'Sign-in cancelled. Going back to menu.',
  },
  returnFlow: {
    continuePrompt: 'Press Enter to go back.',
    actionFailedPrompt: 'Action failed. Press Enter to go back.',
    autoReturn: (seconds: number) => `Returning in ${seconds}s... Press any key to pause.`,
    paused: 'Paused. Press any key to continue.',
    working: 'Running...',
    done: 'Done.',
    failed: 'Failed.',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Customize theme and behavior',
    help: '↑↓ Move | Enter Select | Q Back',
    exitTitle: 'Back',
    colorProfile: 'Color Profile',
    colorProfileHint: 'Terminal color depth: ansi16, ansi256, or truecolor',
    glyphMode: 'Glyph Mode',
    glyphModeHint: 'Character set: ascii, unicode, or auto-detect',
    palette: 'Color Palette',
    paletteHint: 'Base color scheme: antigravity, green or blue',
    accent: 'Accent Color',
    accentHint: 'Highlight color: cyan, magenta, purple, green, blue, or yellow',
    colorProfileAnsi16Hint: 'Basic 16 colors — maximum compatibility',
    colorProfileAnsi256Hint: 'Extended 256 colors — most terminals',
    colorProfileTruecolorHint: 'Full 24-bit color — modern terminals',
    glyphModeAsciiHint: 'ASCII characters only',
    glyphModeUnicodeHint: 'Unicode symbols (◆ • ✓ ✗)',
    glyphModeAutoHint: 'Auto-detect from terminal',
    paletteAntigravityHint: 'Deep space theme (Google Blue & Dark Grey)',
    paletteGreenHint: 'Green-tinted color scheme',
    paletteBlueHint: 'Blue-tinted color scheme',
    accentGreenHint: 'Classic green highlights',
    accentCyanHint: 'Cool cyan highlights',
    accentBlueHint: 'Blue highlights',
    accentYellowHint: 'Warm yellow highlights',
    accentMagentaHint: 'Neon magenta highlights',
    accentPurpleHint: 'Deep gemini purple highlights',
    saveFailed: 'Failed to save settings.',
    saved: 'Settings saved.',
    unchanged: 'No changes.',
  },
} as const;

export function formatCheckFlaggedLabel(flaggedCount?: number): string {
  if (typeof flaggedCount === 'number' && flaggedCount > 0) {
    return `${UI_COPY.mainMenu.checkFlagged} (${flaggedCount})`
  }
  return UI_COPY.mainMenu.checkFlagged
}
